// Generated by CoffeeScript 1.6.2
(function() {
  var Base, asd, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.MousetrapWrapper = {};

  MousetrapWrapper.Base = Base = (function() {
    function Base(lib) {
      this.lib = lib != null ? lib : Mousetrap;
    }

    Base.prototype.events = function() {
      throw new Error('Events method not implemented');
    };

    Base.prototype.attach = function() {
      var event, _i, _len, _ref, _results;

      this.attached = true;
      _ref = this.events();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        _results.push(this.bindCallbackFor(event));
      }
      return _results;
    };

    Base.prototype.reattach = function() {
      if (this.attached) {
        throw new Error('Events already attached');
      }
      return this.attach();
    };

    Base.prototype.detach = function() {
      var event, _i, _len, _ref;

      if (!this.attached) {
        throw new Error('Events not yet attached');
      }
      _ref = this.events();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        this.unbindCallbackFor(event);
      }
      return this.attached = false;
    };

    Base.prototype.bindCallbackFor = function(event) {
      if (!event[1]) {
        throw new Error('Trying to attach an unexisting callback');
      }
      if (event.length === 2) {
        return this.lib.bind(event[0], event[1]);
      } else {
        return this.lib.bind(event[0], event[1], event[2]);
      }
    };

    Base.prototype.unbindCallbackFor = function(event) {
      return this.lib.unbind(event[0]);
    };

    return Base;

  })();

  asd = (function(_super) {
    __extends(asd, _super);

    function asd() {
      _ref = asd.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return asd;

  })(Base);

}).call(this);
